THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 37, in bounced
    result = method(*args, **kw)
  File "/home/jeffch/meta_unsupervised/experiment_0_util/meta_framework.py", line 120, in train_model
    learner_loss.backward()
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jeffch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:35
Running Hebbian: 1 0.01
Encountered Error!
_____
_____
Running Control: 1 0.01
Encountered Error!
_____
_____
Running Hebbian: 1 0.02
Encountered Error!
_____
_____
Running Control: 1 0.02
Encountered Error!
_____
_____
Running Hebbian: 1 0.03
Encountered Error!
_____
_____
Running Control: 1 0.03
Encountered Error!
_____
_____
Running Hebbian: 1 0.04
Encountered Error!
_____
_____
Running Control: 1 0.04
Encountered Error!
_____
_____
Running Hebbian: 1 0.05
Encountered Error!
_____
_____
Running Control: 1 0.05
Encountered Error!
_____
_____
Running Hebbian: 1 0.060000000000000005
Encountered Error!
_____
_____
Running Control: 1 0.060000000000000005
Encountered Error!
_____
_____
Running Hebbian: 1 0.06999999999999999
Encountered Error!
_____
_____
Running Control: 1 0.06999999999999999
Encountered Error!
_____
_____
Running Hebbian: 1 0.08
Encountered Error!
_____
_____
Running Control: 1 0.08
Encountered Error!
_____
_____
Running Hebbian: 1 0.09
Encountered Error!
_____
_____
Running Control: 1 0.09
Encountered Error!
_____
_____
Running Hebbian: 1 0.09999999999999999
Encountered Error!
_____
_____
Running Control: 1 0.09999999999999999
Encountered Error!
_____
_____
Running Hebbian: 1 0.1
Encountered Error!
_____
_____
Running Control: 1 0.1
Encountered Error!
_____
_____
Running Hebbian: 1 0.15000000000000002
Encountered Error!
_____
_____
Running Control: 1 0.15000000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.20000000000000004
Encountered Error!
_____
_____
Running Control: 1 0.20000000000000004
Encountered Error!
_____
_____
Running Hebbian: 1 0.25000000000000006
Encountered Error!
_____
_____
Running Control: 1 0.25000000000000006
Encountered Error!
_____
_____
Running Hebbian: 1 0.30000000000000004
Encountered Error!
_____
_____
Running Control: 1 0.30000000000000004
Encountered Error!
_____
_____
Running Hebbian: 1 0.3500000000000001
Encountered Error!
_____
_____
Running Control: 1 0.3500000000000001
Encountered Error!
_____
_____
Running Hebbian: 1 0.40000000000000013
Encountered Error!
_____
_____
Running Control: 1 0.40000000000000013
Encountered Error!
_____
_____
Running Hebbian: 1 0.45000000000000007
Encountered Error!
_____
_____
Running Control: 1 0.45000000000000007
Encountered Error!
_____
_____
Running Hebbian: 1 0.5000000000000001
Encountered Error!
_____
_____
Running Control: 1 0.5000000000000001
Encountered Error!
_____
_____
Running Hebbian: 1 0.5500000000000002
Encountered Error!
_____
_____
Running Control: 1 0.5500000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.6000000000000002
Encountered Error!
_____
_____
Running Control: 1 0.6000000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.6500000000000001
Encountered Error!
_____
_____
Running Control: 1 0.6500000000000001
Encountered Error!
_____
_____
Running Hebbian: 1 0.7000000000000002
Encountered Error!
_____
_____
Running Control: 1 0.7000000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.7500000000000002
Encountered Error!
_____
_____
Running Control: 1 0.7500000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.8000000000000002
Encountered Error!
_____
_____
Running Control: 1 0.8000000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.8500000000000002
Encountered Error!
_____
_____
Running Control: 1 0.8500000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.9000000000000002
Encountered Error!
_____
_____
Running Control: 1 0.9000000000000002
Encountered Error!
_____
_____
Running Hebbian: 1 0.9500000000000003
Encountered Error!
_____
_____
Running Control: 1 0.9500000000000003
Encountered Error!
_____
_____
Running Hebbian: 1 1.0000000000000004
Encountered Error!
_____
_____
Running Control: 1 1.0000000000000004
Encountered Error!
_____
_____
Running Hebbian: 1 1.0
Encountered Error!
_____
_____
Running Control: 1 1.0
Encountered Error!
_____
_____
Running Hebbian: 1 1.5
Encountered Error!
_____
_____
Running Control: 1 1.5
Encountered Error!
_____
_____
Running Hebbian: 1 2.0
Encountered Error!
_____
_____
Running Control: 1 2.0
Encountered Error!
_____
_____
Running Hebbian: 1 2.5
Encountered Error!
_____
_____
Running Control: 1 2.5
Encountered Error!
_____
_____
Running Hebbian: 1 3.0
Encountered Error!
_____
_____
Running Control: 1 3.0
Encountered Error!
_____
_____
Running Hebbian: 1 3.5
Encountered Error!
_____
_____
Running Control: 1 3.5
Encountered Error!
_____
_____
Running Hebbian: 1 4.0
Encountered Error!
_____
_____
Running Control: 1 4.0
Encountered Error!
_____
_____
Running Hebbian: 1 4.5
Encountered Error!
_____
_____
Running Control: 1 4.5
Encountered Error!
_____
_____
